### ISSUE TITLE
Consider switching to GitHub Pages

### ISSUE THREAD

**Issue by theopolisme** [APerson241/afchistory#1]
Any reason why you're hosting this on Heroku and not GitHub Pages? It's just static content, so the whole webserver behind it is rather overkill. Plus with Heroku's [limits](https://blog.heroku.com/archives/2015/5/7/heroku-free-dynos) on uptime with the free tier, not sure why the 100% free GitHub Pages solution wouldn't be a better option.

Cheers, excited for the future of this tool!

**Comment by APerson241** [comment]
It's not entirely static - it accepts a `user=` parameter, like this: http://afchistory.herokuapp.com/?user=APerson. That parameter (and its usefulness) is the only reason why I'm keeping it on Heroku instead of Pages. I agree that Pages is a "nicer" host (i.e. it's less concerned with making money off me), but it can't do dynamic content.

**Comment by theopolisme** [comment]
I disagree that you're hosting dynamic content... You could just use the url hash for that. All you're doing is prefilling an input on load.

Another nice UX tweak: you can update the hash on keyup, which makes for much easier sharing (just copy/paste the URL). I can submit a pull request if you'd like.

**Comment by APerson241** [comment]
Sure, that sounds great!

**Comment by APerson241** [comment]
Fixed by #2.
